In [140]:
import pandas as pd

# Currently data is no good. It's all one hour

In [141]:
import json

# load from file:
with open('../Data_And_Data_Creation/Hourly_Weather_Data/hourly_past_weather0.json', 'r') as f:
    try:
        weather_dict1 = json.load(f)
    # if the file is empty the ValueError will be thrown
    except ValueError:
        data = {}

In [142]:
weather_df = pd.DataFrame(weather_dict1).T

In [143]:
weather_df

,apparentTemperature,cloudCover,dewPoint,humidity,icon,ozone,precipAccumulation,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97
2015-04-05,45.37,0.16,35.52,0.6,clear-night,NaN,NaN,0,0,NaN,1024.17,Clear,48.94,1428289200,10,32,8.25
2015-04-06,58.51,0.37,42.73,0.56,partly-cloudy-night,NaN,NaN,0,0,NaN,1021.08,Partly Cloudy,58.51,1428375600,10,203,8.76
2015-04-07,38.27,1,40.29,0.87,rain,NaN,NaN,0.0122,0.53,rain,1026.4,Light Rain,43.82,1428462000,6.81,52,10.26
2015-04-08,31.25,1,34.67,0.86,cloudy,NaN,NaN,0.0017,0.04,rain,1024.45,Overcast,38.58,1428548400,5.71,54,11.49
2015-04-09,36.35,1,39.09,0.91,cloudy,NaN,NaN,0,0,NaN,1024.5,Overcast,41.44,1428634800,5.11,110,7.99
2015-04-10,53.46,0.34,48.4,0.83,partly-cloudy-night,NaN,NaN,0,0,NaN,1008.72,Partly Cloudy,53.46,1428721200,7.47,279,9.84
2015-04-11,42.58,0,25.95,0.44,clear-night,NaN,NaN,0,0,NaN,1022.39,Clear,46.72,1428807600,10,327,8.45
2015-04-12,52.35,0.14,39.95,0.63,clear-night,NaN,NaN,0,0,NaN,1026.46,Clear,52.35,1428894000,10,168,4.49
2015-04-13,59.01,0.27,44.08,0.58,partly-cloudy-night,NaN,NaN,0,0,NaN,1021.6,Partly Cloudy,59.01,1428980400,10,191,10.9
2015-04-14,54.71,0.36,34.32,0.46,partly-cloudy-night,NaN,NaN,0,0,NaN,1019.98,Partly Cloudy,54.71,1429066800,10,252,2.53
2015-04-15,59.67,0.17,22.66,0.24,clear-night,NaN,NaN,0,0,NaN,1027.13,Clear,59.67,1429153200,10,21,9.15
2015-04-16,53.06,0.36,42.16,0.66,partly-cloudy-night,NaN,NaN,0,0,NaN,1025.05,Partly Cloudy,53.06,1429239600,10,185,8.42
2015-04-17,62.36,0.39,50.39,0.65,partly-cloudy-night,NaN,NaN,0,0,NaN,1014.45,Partly Cloudy,62.36,1429326000,10,336,3.88
2015-04-18,66.21,0.14,24.6,0.21,clear-night,NaN,NaN,0,0,NaN,1016.17,Clear,66.21,1429412400,10,355,12.24
2015-04-19,41.67,0.3,34.88,0.62,partly-cloudy-night,NaN,NaN,0,0,NaN,1021.72,Partly Cloudy,47.02,1429498800,10,118,12.03
2015-04-20,53.27,NaN,52.65,0.98,fog,NaN,NaN,0,0,NaN,1002.33,Foggy,53.27,1429585200,0.34,76,5.48
2015-04-21,56.42,0,32.68,0.4,clear-night,NaN,NaN,0,0,NaN,1007.72,Clear,56.42,1429671600,10,195,5.03
2015-04-22,51.37,0.19,31.87,0.47,clear-night,NaN,NaN,0,0,NaN,1004.7,Clear,51.37,1429758000,10,276,12.1
2015-04-23,35.23,0.14,20.04,0.4,clear-night,NaN,NaN,0,0,NaN,1009.99,Clear,42.74,1429844400,10,302,15.4
2015-04-24,33.05,0.02,21.2,0.45,clear-night,NaN,NaN,0,0,NaN,1013.17,Clear,40.91,1429930800,10,341,14.83
2015-04-25,51.56,0.24,31.33,0.46,clear-night,NaN,NaN,0,0,NaN,1005.09,Clear,51.56,1430017200,10,27,7.55
2015-04-26,52.78,0.14,28.62,0.39,clear-night,NaN,NaN,0,0,NaN,1005,Clear,52.78,1430103600,10,325,9.74
2015-04-27,53.89,1,34.61,0.48,cloudy,NaN,NaN,0,0,NaN,1006.3,Overcast,53.89,1430190000,10,330,14.73
2015-04-28,61.71,0.13,37.24,0.4,clear-night,NaN,NaN,0,0,NaN,1007.36,Clear,61.71,1430276400,10,346,9.85
2015-04-29,52.53,0.14,42.6,0.69,clear-night,NaN,NaN,0,0,NaN,1005.79,Clear,52.53,1430362800,10,47,10.76
2015-04-30,50.89,0.6,38.3,0.62,partly-cloudy-night,NaN,NaN,0,0,NaN,1012.7,Mostly Cloudy,50.89,1430449200,10,92,6.6
2015-05-01,46.44,0.37,39.59,0.72,partly-cloudy-night,NaN,NaN,0,0,NaN,1015.29,Partly Cloudy,48.02,1430535600,10,187,4.19
2015-05-02,51.02,0.45,37.84,0.6,partly-cloudy-night,NaN,NaN,0,0,NaN,1017.12,Partly Cloudy,51.02,1430622000,10,175,6.57
2015-05-03,61.63,0.1,44.2,0.53,clear-night,NaN,NaN,0,0,NaN,1020.4,Clear,61.63,1430708400,10,167,4.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-05-13,40.94,1,44.78,0.93,rain,NaN,NaN,0.0469,0.72,rain,1008.22,Light Rain,46.65,1494730800,5.16,31,12.89
2017-05-14,56.92,0.29,40.34,0.54,partly-cloudy-night,NaN,NaN,0,0,NaN,1003.22,Partly Cloudy,56.92,1494817200,10,316,17.74
2017-05-15,61.84,0.04,43.35,0.51,clear-night,NaN,NaN,0,0,NaN,1012.38,Clear,61.84,1494903600,10,311,11.79
2017-05-16,69.07,0.12,51.69,0.54,clear-night,NaN,NaN,0,0,NaN,1015.02,Clear,69.07,1494990000,10,216,6.25
2017-05-17,79.73,0.24,62.95,0.57,clear-night,NaN,NaN,0,0,NaN,1013.67,Clear,79.73,1495076400,10,215,9.75
2017-05-18,79.66,0.12,62.05,0.55,clear-night,NaN,NaN,0,0,NaN,1010.91,Clear,79.66,1495162800,10,231,14.7
2017-05-19,74.09,0.23,52.5,0.47,clear-night,NaN,NaN,0,0,NaN,1015.51,Clear,74.09,1495249200,10,21,13.82
2017-05-20,56.41,0.2,44.91,0.65,clear-night,NaN,NaN,0,0,NaN,1026.84,Clear,56.41,1495335600,10,187,7.63
2017-05-21,56.6,1,41.22,0.56,cloudy,NaN,NaN,0,0,NaN,1024.77,Overcast,56.6,1495422000,10,165,8.84
2017-05-22,60.16,0.9,59.04,0.96,partly-cloudy-night,NaN,NaN,0,0,NaN,1014.32,Mostly Cloudy,60.16,1495508400,6.41,303,5.93
2017-05-23,60.57,0.34,49.54,0.67,partly-cloudy-night,NaN,NaN,0,0,NaN,1009.48,Partly Cloudy,60.57,1495594800,10,180,3.52
2017-05-24,59.11,0.34,50.59,0.73,partly-cloudy-night,NaN,NaN,0,0,NaN,1009.63,Partly Cloudy,59.11,1495681200,10,108,10.81
2017-05-25,57.14,1,56.39,0.97,rain,NaN,NaN,0.0554,0.74,rain,998.25,Rain,57.14,1495767600,5.66,42,8.51
2017-05-26,66.79,0.16,52.75,0.61,clear-night,NaN,NaN,0,0,NaN,1008.6,Clear,66.79,1495854000,10,318,10.06
2017-05-27,62.22,0.75,56.28,0.81,partly-cloudy-night,NaN,NaN,0,0,NaN,1012.98,Mostly Cloudy,62.22,1495940400,10,122,5.9
2017-05-28,60.28,0.61,53.62,0.79,partly-cloudy-night,325.7,NaN,0.0008,0.01,rain,1013.37,Mostly Cloudy,60.28,1496026800,9.86,105,8.35
2017-05-29,56.89,0.75,54.18,0.91,partly-cloudy-night,328.1,NaN,0,0,NaN,1019.29,Mostly Cloudy,56.89,1496113200,9.98,107,5.95
2017-05-30,57.32,0.75,56.33,0.97,rain,335.6,NaN,0.0059,0.27,rain,1019.65,Drizzle,57.32,1496199600,6.85,110,5.14
2017-05-31,65.78,0.28,63.29,0.92,rain,348,NaN,0.0077,0.39,rain,1013.8,Drizzle,65.78,1496286000,10,162,2.91
2017-06-01,67.31,0.02,51.09,0.56,clear-night,364.5,NaN,0,0,NaN,1013.72,Clear,67.31,1496372400,10,244,7.35
2017-06-02,63.67,0.01,45.93,0.52,clear-night,386.8,NaN,0,0,NaN,1014.93,Clear,63.67,1496458800,10,345,7.41
2017-06-03,67.03,0.02,46.33,0.47,clear-night,374.6,NaN,0,0,NaN,1015.57,Clear,67.03,1496545200,10,292,5.42
2017-06-04,62.38,0.59,58.65,0.88,rain,349.1,NaN,0.0146,0.56,rain,1011.02,Light Rain,62.38,1496631600,9.99,70,2.27
2017-06-05,62.08,0.75,59.08,0.9,partly-cloudy-night,334.9,NaN,0.0026,0.08,rain,1006.64,Mostly Cloudy,62.08,1496718000,6.64,59,8.85
2017-06-06,54.07,0.72,49.04,0.83,partly-cloudy-night,353.2,NaN,0,0,NaN,1012.79,Mostly Cloudy,54.07,1496804400,9.81,39,7.86
2017-06-07,59.91,0,52.36,0.76,clear-night,346.9,NaN,0,0,NaN,1016.56,Clear,59.91,1496890800,9.9,242,3.98
2017-06-08,60.5,0.66,47.46,0.62,partly-cloudy-night,347,NaN,0,0,NaN,1009.78,Mostly Cloudy,60.5,1496977200,9.92,34,4.25
2017-06-09,74.53,0.07,55.27,0.51,clear-night,357.1,NaN,0,0,NaN,1011.21,Clear,74.53,1497063600,10,224,7.23
2017-06-10,75.51,0.07,61.82,0.63,clear-night,337,NaN,0,0,NaN,1016.4,Clear,75.51,1497150000,10,175,4.83
2017-06-11,77.38,0.07,63.7,0.63,clear-night,315.98,NaN,0,0,NaN,1016.9,Clear,77.38,1497236400,10,217,8.02

In [133]:
weather_df['hour'] = 0

In [134]:
for num in range(1,24):
    with open('../Data_And_Data_Creation/Hourly_Weather_Data/hourly_past_weather'+str(num)+'.json', 'r') as f:
        try:
            weather_dict1 = json.load(f)
        # if the file is empty the ValueError will be thrown
        except ValueError:
            data = {}
            
    weather_df_partial = pd.DataFrame(weather_dict1).T
    weather_df_partial['hour'] = num
    weather_df = pd.concat([weather_df,weather_df_partial])

In [135]:
weather_df['Date'] = weather_df.index

In [136]:
df =pd.read_csv('../Data_And_Data_Creation/advanced_welcome_table_summed.csv')

In [139]:
weather_df[weather_df['Date'] == "2015-04-04"]

,apparentTemperature,cloudCover,dewPoint,humidity,icon,ozone,precipAccumulation,precipIntensity,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed,hour,Date
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,0,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,1,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,2,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,3,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,4,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,5,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,6,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,7,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,8,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,9,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,10,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,11,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,12,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,13,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,14,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,15,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,16,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,17,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,18,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,19,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,20,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,21,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,22,2015-04-04
2015-04-04,39.95,0,18.82,0.36,clear-night,NaN,NaN,0,0,NaN,1020.49,Clear,43.98,1428202800,10,305,6.97,23,2015-04-04

In [115]:
df= df.rename({'Unnamed: 0': 'Date'}, axis =1)

In [116]:
cols = ['Date']
df.join(weather_df.set_index(cols), on=cols)

,Date,total_visitors,total_new,total_returns,from_11201,Temperature,avg_visits_per_hour,avg_returns_per_hour,avg_new_per_hour,avg_from_11201_per_hour,...,precipProbability,precipType,pressure,summary,temperature,time,visibility,windBearing,windSpeed,hour
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,0.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,1.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,2.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,3.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,4.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,5.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,6.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,7.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,8.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,9.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,10.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,11.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,12.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,13.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,14.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,15.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,16.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,17.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,18.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,19.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,20.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,21.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,22.0
0,2015-08-20,37,37.0,0.0,NaN,82.07,18.50,0.00,18.50,NaN,...,0,NaN,1014.89,Overcast,78.23,1440126000,10,144,11.64,23.0
1,2015-08-22,80,80.0,0.0,NaN,82.16,20.00,0.00,20.00,NaN,...,0,NaN,1017.35,Clear,74.6,1440298800,10,9,6.14,0.0
1,2015-08-22,80,80.0,0.0,NaN,82.16,20.00,0.00,20.00,NaN,...,0,NaN,1017.35,Clear,74.6,1440298800,10,9,6.14,1.0
1,2015-08-22,80,80.0,0.0,NaN,82.16,20.00,0.00,20.00,NaN,...,0,NaN,1017.35,Clear,74.6,1440298800,10,9,6.14,2.0
1,2015-08-22,80,80.0,0.0,NaN,82.16,20.00,0.00,20.00,NaN,...,0,NaN,1017.35,Clear,74.6,1440298800,10,9,6.14,3.0
1,2015-08-22,80,80.0,0.0,NaN,82.16,20.00,0.00,20.00,NaN,...,0,NaN,1017.35,Clear,74.6,1440298800,10,9,6.14,4.0
1,2015-08-22,80,80.0,0.0,NaN,82.16,20.00,0.00,20.00,NaN,...,0,NaN,1017.35,Clear,74.6,1440298800,10,9,6.14,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,2019-04-09,28,1.0,27.0,26.0,45.00,14.00,13.50,0.50,13.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
684,2019-04-11,20,10.0,10.0,10.0,51.14,10.00,5.00,5.00,5.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
685,2019-04-13,111,73.0,38.0,25.0,73.71,27.75,9.50,18.25,6.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,2019-04-14,74,22.0,52.0,31.0,69.97,18.50,13.00,5.50,7.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,2019-04-16,18,11.0,7.0,7.0,64.02,9.00,3.50,5.50,3.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,2019-04-18,28,10.0,18.0,22.0,60.74,14.00,9.00,5.00,11.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,2019-04-20,91,63.0,25.0,31.0,65.15,22.75,6.25,15.75,7.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,2019-04-21,53,37.0,16.0,10.0,63.34,13.25,4.00,9.25,2.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
691,2019-04-23,67,43.0,25.0,21.0,74.20,33.50,12.50,21.50,10.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
692,2019-04-25,39,22.0,17.0,13.0,61.91,19.50,8.50,11.00,6.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
693,2019-04-27,86,52.0,34.0,23.0,59.26,21.50,8.50,13.00,5.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,2019-04-28,49,18.0,31.0,28.0,52.44,12.25,7.75,4.50,7.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
695,2019-04-30,17,4.0,13.0,13.0,61.16,8.50,6.50,2.00,6.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
696,2019-05-02,35,19.0,16.0,13.0,73.57,17.50,8.00,9.50,6.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,2019-05-04,103,61.0,42.0,40.0,67.73,25.75,10.50,15.25,10.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
698,2019-05-05,65,10.0,55.0,40.0,57.00,16.25,13.75,2.50,10.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
699,2019-05-07,8,3.0,5.0,7.0,69.32,4.00,2.50,1.50,3.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
700,2019-05-09,27,11.0,16.0,24.0,57.90,13.50,8.00,5.50,12.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,2019-05-11,88,46.0,42.0,42.0,69.02,22.00,10.50,11.50,10.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
702,2019-05-12,20,10.0,10.0,16.0,58.04,5.00,2.50,2.50,4.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
703,2019-05-14,31,4.0,27.0,27.0,50.81,15.50,13.50,2.00,13.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
704,2019-05-16,23,7.0,16.0,11.0,71.05,11.50,8.00,3.50,5.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,2019-05-18,71,42.0,26.0,15.0,73.44,17.75,6.50,10.50,3.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
706,2019-05-19,96,40.0,56.0,53.0,74.85,24.00,14.00,10.00,13.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,2019-05-21,22,12.0,10.0,15.0,71.90,11.00,5.00,6.00,7.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
708,2019-05-23,32,6.0,26.0,17.0,70.36,16.00,13.00,3.00,8.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
709,2019-05-25,93,68.0,25.0,21.0,67.36,23.25,6.25,17.00,5.25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
710,2019-05-26,103,66.0,37.0,16.0,86.15,25.75,9.25,16.50,4.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
711,2019-05-28,36,4.0,32.0,34.0,69.25,18.00,16.00,2.00,17.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,2019-05-30,34,7.0,27.0,27.0,63.77,17.00,13.50,3.50,13.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [117]:
df_sh = df[['Date', 'avg_visits_per_hour']]

In [118]:
weather_df.columns

Index([u'apparentTemperature',          u'cloudCover',            u'dewPoint',
                  u'humidity',                u'icon',               u'ozone',
        u'precipAccumulation',     u'precipIntensity',   u'precipProbability',
                u'precipType',            u'pressure',             u'summary',
               u'temperature',                u'time',          u'visibility',
               u'windBearing',           u'windSpeed',                u'hour',
                      u'Date'],
      dtype='object')

In [119]:
weather_df_sh = weather_df[['temperature', 'cloudCover', 'humidity', 'precipIntensity', 'hour']].astype('float')

In [120]:
weather_df_sh['Date'] = weather_df['Date']

In [121]:
df_sh = df_sh.join(weather_df_sh.set_index(cols), on=cols)

In [129]:
df_sh

,Date,avg_visits_per_hour,temperature,cloudCover,humidity,precipIntensity,hour
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,0.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,1.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,2.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,3.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,4.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,5.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,6.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,7.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,8.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,9.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,10.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,11.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,12.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,13.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,14.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,15.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,16.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,17.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,18.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,19.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,20.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,21.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,22.0
0,2015-08-20,18.50,78.23,1.00,0.78,0.0,23.0
1,2015-08-22,20.00,74.60,0.18,0.53,0.0,0.0
1,2015-08-22,20.00,74.60,0.18,0.53,0.0,1.0
1,2015-08-22,20.00,74.60,0.18,0.53,0.0,2.0
1,2015-08-22,20.00,74.60,0.18,0.53,0.0,3.0
1,2015-08-22,20.00,74.60,0.18,0.53,0.0,4.0
1,2015-08-22,20.00,74.60,0.18,0.53,0.0,5.0
...,...,...,...,...,...,...,...
683,2019-04-09,14.00,NaN,NaN,NaN,NaN,NaN
684,2019-04-11,10.00,NaN,NaN,NaN,NaN,NaN
685,2019-04-13,27.75,NaN,NaN,NaN,NaN,NaN
686,2019-04-14,18.50,NaN,NaN,NaN,NaN,NaN
687,2019-04-16,9.00,NaN,NaN,NaN,NaN,NaN
688,2019-04-18,14.00,NaN,NaN,NaN,NaN,NaN
689,2019-04-20,22.75,NaN,NaN,NaN,NaN,NaN
690,2019-04-21,13.25,NaN,NaN,NaN,NaN,NaN
691,2019-04-23,33.50,NaN,NaN,NaN,NaN,NaN
692,2019-04-25,19.50,NaN,NaN,NaN,NaN,NaN
693,2019-04-27,21.50,NaN,NaN,NaN,NaN,NaN
694,2019-04-28,12.25,NaN,NaN,NaN,NaN,NaN
695,2019-04-30,8.50,NaN,NaN,NaN,NaN,NaN
696,2019-05-02,17.50,NaN,NaN,NaN,NaN,NaN
697,2019-05-04,25.75,NaN,NaN,NaN,NaN,NaN
698,2019-05-05,16.25,NaN,NaN,NaN,NaN,NaN
699,2019-05-07,4.00,NaN,NaN,NaN,NaN,NaN
700,2019-05-09,13.50,NaN,NaN,NaN,NaN,NaN
701,2019-05-11,22.00,NaN,NaN,NaN,NaN,NaN
702,2019-05-12,5.00,NaN,NaN,NaN,NaN,NaN
703,2019-05-14,15.50,NaN,NaN,NaN,NaN,NaN
704,2019-05-16,11.50,NaN,NaN,NaN,NaN,NaN
705,2019-05-18,17.75,NaN,NaN,NaN,NaN,NaN
706,2019-05-19,24.00,NaN,NaN,NaN,NaN,NaN
707,2019-05-21,11.00,NaN,NaN,NaN,NaN,NaN
708,2019-05-23,16.00,NaN,NaN,NaN,NaN,NaN
709,2019-05-25,23.25,NaN,NaN,NaN,NaN,NaN
710,2019-05-26,25.75,NaN,NaN,NaN,NaN,NaN
711,2019-05-28,18.00,NaN,NaN,NaN,NaN,NaN
712,2019-05-30,17.00,NaN,NaN,NaN,NaN,NaN

In [123]:
df_sh_0 = df_sh[df_sh['hour'] == 0]

In [124]:
df_sh_0.corr()

,avg_visits_per_hour,temperature,cloudCover,humidity,precipIntensity,hour
avg_visits_per_hour,1.000000,0.282444,-0.015485,-0.078151,-0.096044,NaN
temperature,0.282444,1.000000,0.125740,0.217781,-0.079035,NaN
cloudCover,-0.015485,0.125740,1.000000,0.500355,0.098158,NaN
humidity,-0.078151,0.217781,0.500355,1.000000,0.049468,NaN
precipIntensity,-0.096044,-0.079035,0.098158,0.049468,1.000000,NaN
hour,NaN,NaN,NaN,NaN,NaN,NaN

In [126]:
df_sh_0 = df_sh[df_sh['hour'] == 1]
df_sh_0.corr()

,avg_visits_per_hour,temperature,cloudCover,humidity,precipIntensity,hour
avg_visits_per_hour,1.000000,0.282444,-0.015485,-0.078151,-0.096044,NaN
temperature,0.282444,1.000000,0.125740,0.217781,-0.079035,NaN
cloudCover,-0.015485,0.125740,1.000000,0.500355,0.098158,NaN
humidity,-0.078151,0.217781,0.500355,1.000000,0.049468,NaN
precipIntensity,-0.096044,-0.079035,0.098158,0.049468,1.000000,NaN
hour,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
df_sh_0 = df_sh[df_sh['hour'] == 12]
df_sh_0.corr()

,avg_visits_per_hour,temperature,cloudCover,humidity,precipIntensity,hour
avg_visits_per_hour,1.000000,0.282444,-0.015485,-0.078151,-0.096044,NaN
temperature,0.282444,1.000000,0.125740,0.217781,-0.079035,NaN
cloudCover,-0.015485,0.125740,1.000000,0.500355,0.098158,NaN
humidity,-0.078151,0.217781,0.500355,1.000000,0.049468,NaN
precipIntensity,-0.096044,-0.079035,0.098158,0.049468,1.000000,NaN
hour,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
df_sh = df_sh.set_index('Date')

In [16]:
df_sh.head()

            avg_visits_per_hour
Date
2015-08-20                18.50
2015-08-22                20.00
2015-08-23                23.75
2015-08-26                21.00
2015-08-28                 8.00

In [17]:
df_sh.loc['2015-08-20'][0]

18.5

In [18]:
temp_vals = []
for i,x in weather_df_sh.iterrows():
    try:
        temp_vals.append(df_sh.loc[i][0])
    except:
        temp_vals.append('no')

In [19]:
temp_vals

['no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 18.5,
 'no',
 20.0,
 23.75,
 'no',
 'no',
 21.0,
 'no',
 8.0,
 26.0,
 17.5,
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 14.5,
 'no',
 22.75,
 23.5,
 'no',
 'no',
 'no',
 12.0,
 'no',
 23.5,
 17.75,
 'no',
 'no',
 'no',
 16.5,
 'no',
 14.0,
 18.5,
 'no',
 'no',
 'no',
 17.5,
 'no',
 11.0,
 24.75,
 'no',
 'no',
 'no',
 14.5,
 'no',
 20.5,
 20.0,
 'no',
 'no',
 'no',
 38.5,
 'no',
 'no',
 19.25,
 'no',
 'no',
 'no',
 9.0,
 'no',
 20.5,
 'no',
 'no',
 'no',
 'no',
 4.0,
 'no',
 11.0,
 16.5,
 'no',
 'no',
 'no',
 24.5,
 'no',
 30.25,
 23.5,
 'no',
 'no',
 'no',
 4.5,
 'no',
 18.75,
 27.5,
 'no',
 'no',
 'no',
 15.0,
 'no',
 20.75,
 14.0,
 'no',
 'no',
 'no',
 'no',
 'no',
 16.75,
 23.25,
 'no',
 'no',
 'no',
 5.5,
 'no',
 11.5,
 21.0,
 'no',
 'no',
 'no',
 21.5,
 'no',
 23.25,
 28.75,
 'no',
 'no',
 'no',
 7.0,
 'no',
 7.25,
 19.75,
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 10.0,
 'no',
 19.75,
 22.75,
 'no',
 'no',
 'no',
 17.5,
 'no',
 28.0,
 13.0,
 5.5,
 'no',
 'no',
 17.0,
 'no',
 'no',
 'no',
 'no',
 1.0,
 'no',
 10.5,
 'no',
 17.5,
 25.0,
 'no',
 9.0,
 'no',
 14.5,
 'no',
 25.5,
 20.75,
 8.5,
 5.5,
 'no',
 8.0,
 'no',
 10.5,
 3.5,
 'no',
 4.5,
 'no',
 42.5,
 'no',
 31.75,
 33.75,
 'no',
 2.0,
 'no',
 13.0,
 'no',
 26.75,
 45.5,
 'no',
 11.0,
 'no',
 22.0,
 'no',
 19.5,
 27.5,
 'no',
 8.5,
 'no',
 17.5,
 'no',
 24.75,
 30.75,
 'no',
 11.0,
 'no',
 11.0,
 'no',
 29.75,
 21.0,
 'no',
 16.0,
 'no',
 21.0,
 'no',
 23.25,
 30.0,
 'no',
 6.0,
 'no',
 22.5,
 'no',
 18.5,
 18.75,
 'no',
 7.0,
 'no',
 11.5,
 'no',
 2.25,
 25.0,
 'no',
 9.5,
 'no',
 14.5,
 'no',
 29.75,
 22.5,
 'no',
 7.0,
 'no',
 7.0,
 'no',
 90.5,
 23.75,
 'no',
 44.5,
 'no',
 26.0,
 'no',
 29.75,
 11.5,
 'no',
 13.0,
 'no',
 18.0,
 'no',
 17.25,
 21.0,
 'no',
 12.5,
 'no',
 9.0,
 'no',
 17.75,
 23.75,
 'no',
 16.0,
 'no',
 23.5,
 'no',
 19.0,
 17.25,
 'no',
 1.0,
 1.0,
 24.5,
 'no',
 16.5,
 26.25,
 'no',
 10.5,
 'no',
 17.5,
 'no',
 37.0,
 14.75,
 'no',
 'no',
 'no',
 29.5,
 'no',
 19.25,
 32.25,
 'no',
 16.0,
 'no',
 21.0,
 'no',
 33.75,
 32.75,
 'no',
 12.0,
 'no',
 13.5,
 'no',
 18.5,
 44.0,
 'no',
 19.5,
 'no',
 21.5,
 'no',
 23.5,
 29.5,
 'no',
 26.0,
 'no',
 10.0,
 'no',
 19.0,
 33.0,
 'no',
 21.0,
 'no',
 8.0,
 'no',
 26.75,
 19.5,
 'no',
 19.0,
 'no',
 18.5,
 'no',
 13.25,
 18.0,
 'no',
 11.0,
 'no',
 25.0,
 'no',
 19.5,
 22.0,
 'no',
 38.5,
 'no',
 22.0,
 'no',
 18.25,
 26.25,
 'no',
 24.0,
 'no',
 7.5,
 'no',
 15.75,
 15.75,
 'no',
 30.0,
 'no',
 27.5,
 'no',
 21.5,
 28.25,
 'no',
 26.0,
 'no',
 33.0,
 'no',
 18.25,
 28.75,
 'no',
 32.5,
 'no',
 15.0,
 'no',
 26.25,
 32.0,
 'no',
 30.5,
 'no',
 24.5,
 'no',
 28.0,
 25.75,
 'no',
 20.5,
 'no',
 'no',
 'no',
 23.0,
 20.75,
 'no',
 23.0,
 'no',
 16.0,
 'no',
 18.5,
 19.0,
 'no',
 20.0,
 'no',
 9.0,
 'no',
 16.25,
 26.75,
 'no',
 25.5,
 'no',
 14.5,
 'no',
 12.75,
 12.75,
 'no',
 11.0,
 'no',
 14.0,
 'no',
 20.75,
 28.25,
 'no',
 17.0,
 'no',
 26.5,
 'no',
 12.5,
 21.5,
 'no',
 17.5,
 'no',
 12.5,
 'no',
 12.5,
 20.75,
 'no',
 19.0,
 'no',
 9.0,
 'no',
 19.75,
 21.75,
 'no',
 32.0,
 'no',
 14.5,
 'no',
 20.0,
 28.5,
 'no',
 17.0,
 'no',
 13.5,
 'no',
 32.0,
 2.75,
 'no',
 12.0,
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 4.5,
 'no',
 8.5,
 'no',
 3.75,
 13.25,
 'no',
 14.0,
 'no',
 11.0,
 'no',
 11.5,
 13.75,
 'no',
 6.5,
 'no',
 4.0,
 'no',
 3.0,
 12.75,
 'no',
 6.5,
 'no',
 19.5,
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 5.5,
 'no',
 7.5,
 'no',
 3.75,
 2.75,
 'no',
 10.0,
 'no',
 17.0,
 'no',
 9.25,
 17.0,
 'no',
 7.0,
 'no',
 20.0,
 'no',
 17.0,
 10.75,
 'no',
 10.5,
 'no',
 18.0,
 'no',
 16.75,
 20.0,
 'no',
 5.0,
 'no',
 12.0,
 'no',
 18.25,
 11.75,
 'no',
 11.5,
 'no',
 'no',
 'no',
 9.25,
 4.75,
 'no',
 13.5,
 'no',
 13.0,
 'no',
 30.25,
 31.0,
 'no',
 38.0,
 'no',
 37.0,
 'no',
 28.75,
 16.0,
 'no',
 10.0,
 'no',
 12.0,
 'no',
 10.25,
 21.0,
 'no',
 20.0,
 'no',
 23.0,
 'no',
 8.5,
 20.0,
 'no',
 'no',
 'no',
 9.5,
 'no',
 11.25,
 17.75,
 'no',
 8.5,
 'no',
 8.0,
 'no',
 29.0,
 20.75,
 'no',
 9.0,
 'no',
 19.5,
 'no',
 17.5,
 23.75,
 'no',
 9.5,
 'no',
 'no',
 'no',
 14.75,
 20.0,
 'no',
 26.5,
 'no',
 39.0,
 'no',
 23.75,
 29.25,
 'no',
 23.0,
 'no',
 13.0,
 'no',
 14.75,
 33.25,
 'no',
 7.0,
 'no',
 13.5,
 'no',
 20.5,
 19.0,
 'no',
 21.0,
 'no',
 15.5,
 'no',
 19.25,
 28.25,
 'no',
 18.5,
 'no',
 17.0,
 'no',
 1.25,
 19.25,
 'no',
 13.5,
 'no',
 15.5,
 'no',
 22.25,
 28.25,
 'no',
 8.0,
 'no',
 4.0,
 'no',
 13.75,
 23.0,
 'no',
 12.5,
 'no',
 10.5,
 'no',
 24.0,
 9.25,
 'no',
 13.5,
 'no',
 25.0,
 'no',
 21.75,
 16.5,
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 18.5,
 'no',
 20.0,
 23.75,
 'no',
 'no',
 21.0,
 'no',
 8.0,
 26.0,
 17.5,
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 14.5,
 'no',
 22.75,
 23.5,
 'no',
 'no',
 'no',
 12.0,
 'no',
 23.5,
 17.75,
 'no',
 'no',
 'no',
 16.5,
 'no',
 14.0,
 18.5,
 'no',
 'no',
 'no',
 17.5,
 'no',
 11.0,
 24.75,
 'no',
 'no',
 'no',
 14.5,
 'no',
 20.5,
 20.0,
 'no',
 'no',
 'no',
 38.5,
 'no',
 'no',
 19.25,
 'no',
 'no',
 ...]